# Custom Package Selection

# ===== Network & Security =====
apk luci-app-adguardhome # AdGuard Home
apk luci-i18n-adguardhome-zh-cn

# ===== Proxy Ecosystem =====
apk luci-app-openclash
apk geoview xray-core sing-box hysteria kmod-nft-socket kmod-nft-tproxy luci-app-passwall2 luci-i18n-passwall2-zh-cn
apk luci-app-ssr-plus
apk luci-i18n-homeproxy-zh-cn
apk luci-i18n-daed-zh-cn
