# Package selection (uncomment to enable)
apk luci-app-adguardhome # AdGuard Home
apk luci-i18n-nlbwmon-zh-cn
apk luci-i18n-ddns-go-zh-cn
apk luci-i18n-wol-zh-cn
apk luci-i18n-timewol-zh-cn
apk luci-i18n-smartdns-zh-cn
apk luci-i18n-upnp-zh-cn
apk luci-app-openclash
apk luci-app-passwall2
apk luci-i18n-passwall-zh-cn
apk luci-app-ssr-plus
apk luci-i18n-homeproxy-zh-cn
apk luci-i18n-nikki-zh-cn
